name: Terraform CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./01-terraform-init
        run: terraform init -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" -backend-config="region=eu-north-1"

      - name: Terraform Validate
        working-directory: ./01-terraform-init
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./01-terraform-init
        run: terraform plan -var-file=dev.tfvars

      # Repeat similar steps for other layers (02-vpc, 03-alb, 04-ec2) as needed